name: dr_scan_graduation_project
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:

  font_awesome_flutter: ^10.4.0
  loading_indicator: ^3.1.0
  flutter_custom_clippers: ^2.1.0
  flutter_spinkit: ^5.1.0
  animated_splash_screen: ^1.3.0
  loading_animation_widget: ^1.2.0+4
  icons_plus: ^4.0.0
  text_divider: ^1.0.0
  smooth_page_indicator: ^1.0.1
  numberpicker: ^2.1.1
  page_transition: "^2.0.9"
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  loading_overlay: ^0.3.0
  responsive_framework: ^0.2.0
  wtf_sliding_sheet: ^1.1.3
  flutter_screenutil: ^5.7.0
  image_picker: ^0.8.8
  camera: ^0.10.3+2
  textfield_search: ^0.10.0
  google_sign_in: ^6.1.0
  firebase_core: ^2.10.0
  http: ^0.13.6
  firebase_auth: ^4.4.2
  flutter_facebook_auth: ^5.0.8

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  get: ^4.6.5
  shared_preferences: ^2.1.1
  connectivity_plus: ^4.0.1
  async: ^2.10.0
  path: ^1.8.2
  path_provider: ^2.0.15
  equatable: ^2.0.5
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Abril Fatface
      fonts:
        - asset: assets/fonts/AbrilFatface-Regular.ttf
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-SemiBold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf




  uses-material-design: true


  assets:
    - assets/images/
    - assets/data/

